name: Tests

on:
  push:
    branches:
      - main

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
        - run: node --version
        - run: npm --version
        - uses: actions/checkout@v3
        - run: npm install
        - run: node test.js
        - run: node microservices/users/users.js
        - run: node microservices/users/payments.js
        - run: node microservices/users/orders.js
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: jest-test
        run: npm test