name: Tests

on:
  push:
    branches:
      - main

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
        - run: node --version
        - run: npm --version
        - uses: actions/checkout@v3
        - run: npm install
        - run: node main.js
        - run: node microservices/users/users.js
  build-payments:
    runs-on: ubuntu-latest
    container: node:16
    steps:
        - run: node --version
        - run: npm --version
        - uses: actions/checkout@v3
        - run: npm install
        - run: node main.js
        #- run: node microservices/users/users.js
        - run: node microservices/payments/payments.js
        #- run: node microservices/users/orders.js
  buildorders:
    runs-on: ubuntu-latest
    container: node:16
    steps:
        - run: node --version
        - run: npm --version
        - uses: actions/checkout@v3
        - run: npm install
        - run: node main.js
        #- run: node microservices/users/users.js
        #- run: node microservices/users/payments.js
        - run: node microservices/orders/orders.js
        # - run: npm test
  run-tests:
    runs-on: ubuntu-latest
      steps:
        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
            with:
          time: 60s
        - name: Checkout
          uses: actions/checkout@v3
        - name: jest-test
            run: npm test